baseURL = 'http://example.org/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'Example Site'
theme = 'Farallon'


[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[Params]
  search=false
  description = 'A simple and fast blog framework written in Go.'
  toc = true
  mainSections = ['story']

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]

[menu]
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="1"
  [[menu.main]]
  name="分类"
  url="/categories/"
  weight="2"
